### ISSUE TITLE
docs: server example does not build

### ISSUE THREAD

**Issue by greenpau** [emersion/go-smtp#178] opened 2022-01-31 22:37 UTC
The https://github.com/emersion/go-smtp#server example does not build:

```
$ go run main.go
# command-line-arguments
./main.go:17:9: cannot use &Session{} (type *Session) as type smtp.Session in return argument:
        *Session does not implement smtp.Session (wrong type for Mail method)
                have Mail(string, *smtp.MailOptions) error
                want Mail(string, smtp.MailOptions) error
./main.go:58:21: cannot use be (type *Backend) as type smtp.Backend in argument to smtp.NewServer:
        *Backend does not implement smtp.Backend (missing AnonymousLogin method)
```

**Comment by emersion** [comment] 2022-01-31 22:40
Duplicate of https://github.com/emersion/go-smtp/issues/159

**Closed by emersion** 2022-01-31 22:40 UTC

**Comment by greenpau** [comment] 2022-01-31 22:47
Just in case someone needs the fix.

```diff
19a20,27
> func (bkd *Backend) AnonymousLogin(_ *smtp.ConnectionState) (smtp.Session, error) {
>       return &Session{}, nil
> }
>
> func (bkd *Backend) Login(_ *smtp.ConnectionState, username, password string) (smtp.Session, error) {
>       return &Session{}, nil
> }
>
30c38
< func (s *Session) Mail(from string, opts *smtp.MailOptions) error {
---
> func (s *Session) Mail(from string, opts smtp.MailOptions) error {
```

**Comment by greenpau** [comment] 2022-01-31 22:53
Also, to exit telnet session, type `QUIT`. i.e.

```
$ telnet localhost 1025
EHLO localhost
AUTH PLAIN
AHVzZXJuYW1lAHBhc3N3b3Jk
MAIL FROM:<root@nsa.gov>
RCPT TO:<root@gchq.gov.uk>
DATA
foo
bar
.
QUIT
```
