### ISSUE TITLE
examples in README outdated

### ISSUE THREAD

**Issue by hadmut** [emersion/go-smtp#166] opened 2021-11-04 20:05 UTC
Hi, 
when trying to compile the SERVER example from the README (exact copy/paste) I do get

./main.go:17:9: cannot use &Session literal (type *Session) as type smtp.Session in return argument:
        *Session does not implement smtp.Session (wrong type for Mail method)
                have Mail(string, *smtp.MailOptions) error
                want Mail(string, smtp.MailOptions) error
./main.go:58:21: cannot use be (type *Backend) as type smtp.Backend in argument to smtp.NewServer:
        *Backend does not implement smtp.Backend (missing AnonymousLogin method)

Seems like the examples didn't follow API changes.

**Comment by emersion** [comment] 2021-11-04 20:14
Duplicate of https://github.com/emersion/go-smtp/issues/159

**Closed by emersion** 2021-11-04 20:14 UTC
