### ISSUE TITLE
Fix example server

### ISSUE THREAD

**Issue by tegk** [emersion/go-smtp#34] opened 2019-04-02 22:47 UTC
```
.\sm.go:17:34: undefined: smtp.ConnectionState
.\sm.go:17:84: undefined: smtp.Session
.\sm.go:25:43: undefined: smtp.ConnectionState
.\sm.go:25:66: undefined: smtp.Session
.\sm.go:38:26: undefined: from
.\sm.go:64:3: s.ReadTimeout undefined (type *smtp.Server has no field or method ReadTimeout)
.\sm.go:65:3: s.WriteTimeout undefined (type *smtp.Server has no field or method WriteTimeout)

```

**Comment by foxcpp** [comment] 2019-04-02 22:58
The master branch of go-smtp includes one breaking change (#31) and a new feature (#33) since the latest release. I guess you tried to run the example from the master branch on go-smtp 0.10 (or even 0.9, these ConnectionState errors are suspicious).

There is however one real compilation issue caused by a typo (addressed in #35).

@emersion, I think we should push code for next release to a separate branch in the future (like, `dev` branch) to prevent confusion.

**Comment by emersion** [comment] 2019-04-03 06:48
There was a small amount of time during which the README hadn't yet been updated...

>I think we should push code for next release to a separate branch in the future (like, dev branch) to prevent confusion.

That's not how Go modules are supposed to work. People using Go modules will use the latest release, not the latest commit. So we should be fine pushing breaking changes to master as long as we release a new major semver next.

**Comment by foxcpp** [comment] 2019-04-03 07:29
That's not how Go modules are supposed to work. People using Go modules will use the latest release, not the latest commit. So we should be fine pushing breaking changes to master as long as we release a new major semver next.That's is the problem, people see readme on GitHub from master, godoc shows documentation for master. But when people actually import it - they get different version (latest release).

**Comment by foxcpp** [comment] 2019-04-03 07:31
Woops. My mobile email client messed up quote.--That's is the problem, people see readme on GitHub from master, godoc shows documentation for master. But when people actually import it - they get different version (latest release).

**Comment by emersion** [comment] 2019-04-03 07:44
(Edited your comment to fix the quote)

Hmm. I wonder how other projects handle this? Really not a fan of having two branches.

**Comment by foxcpp** [comment] 2019-04-03 14:01
> Hmm. I wonder how other projects handle this? Really not a fan of having two branches.
Well, big projects (I checked IFPS and Hugo) seem to use two branches. Smaller ones just ignore these issues.

Also, not pushing unstable to master is better for developers who use GOPATH instead of modules. And yes, there are still valid reasons to not use them (tooling support is immature).
But this is not relevant to us anyway since we are at 0.X.

**Comment by Xeoncross** [comment] 2019-05-26 05:34
Just got bit by this. I was using GOPATH then I realized I probably needed to pull master. 🤦‍♂

**Comment by emersion** [comment] 2019-05-26 17:32
Since 0.11 has been released, the example should work again

**Closed by emersion** 2019-05-26 17:32 UTC
